const borderStyles = {
  border1Top: {
    position: 'fixed',
    top: 0,
    left: 0,
    height: 20,
    width: '100vw',
    backgroundColor: '#fff',
  },
  border1Right: {
    position: 'fixed',
    top: 0,
    right: 0,
    height: '100vh',
    width: 20,
    backgroundColor: '#fff',
  },
  border1Bottom: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    height: 20,
    width: '100vw',
    backgroundColor: '#fff',
  },
  border1Left: {
    position: 'fixed',
    top: 0,
    left: 0,
    height: '100vh',
    width: 20,
    backgroundColor: '#fff',
  },
  border2Top: {
    position: 'fixed',
    top: 20,
    left: 20,
    height: 20,
    width: 'calc(100vw - 40px)',
    backgroundColor: '#f7f7f7',
  },
  border2Right: {
    position: 'fixed',
    top: 20,
    right: 20,
    height: 'calc(100vh - 40px)',
    width: 20,
    backgroundColor: '#f7f7f7',
  },
  border2Bottom: {
    position: 'fixed',
    bottom: 20,
    left: 20,
    height: 20,
    width: 'calc(100vw - 40px)',
    backgroundColor: '#f7f7f7',
  },
  border2Left: {
    position: 'fixed',
    top: 20,
    left: 20,
    height: 'calc(100vh - 40px)',
    width: 20,
    backgroundColor: '#f7f7f7',
  },
};

export default borderStyles;
